// Mocks generated by Mockito 5.4.0 from annotations
// in dartsmiths/test/features/profile/data/models/get_user_profile_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dartsmiths/features/profile/data/models/user_profile_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserProfileModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileModel extends _i1.Mock implements _i2.UserProfileModel {
  MockUserProfileModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get profilePicture => (super.noSuchMethod(
        Invocation.getter(#profilePicture),
        returnValue: '',
      ) as String);
  @override
  String get fullName => (super.noSuchMethod(
        Invocation.getter(#fullName),
        returnValue: '',
      ) as String);
  @override
  String get userName => (super.noSuchMethod(
        Invocation.getter(#userName),
        returnValue: '',
      ) as String);
  @override
  String get career => (super.noSuchMethod(
        Invocation.getter(#career),
        returnValue: '',
      ) as String);
  @override
  String get bio => (super.noSuchMethod(
        Invocation.getter(#bio),
        returnValue: '',
      ) as String);
  @override
  int get userFollower => (super.noSuchMethod(
        Invocation.getter(#userFollower),
        returnValue: 0,
      ) as int);
  @override
  int get userFollowing => (super.noSuchMethod(
        Invocation.getter(#userFollowing),
        returnValue: 0,
      ) as int);
  @override
  int get numberOfPosts => (super.noSuchMethod(
        Invocation.getter(#numberOfPosts),
        returnValue: 0,
      ) as int);
  @override
  List<Object> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object>[],
      ) as List<Object>);
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
