// Mocks generated by Mockito 5.4.0 from annotations
// in dark_knights/test/features/authentication/data/repositories/authentication_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dark_knights/core/network/network_info.dart' as _i3;
import 'package:dark_knights/features/Authentication/data/datasources/authenication_remote_data_sources.dart'
    as _i5;
import 'package:dark_knights/features/Authentication/data/datasources/authentication_local_data_source.dart'
    as _i7;
import 'package:dark_knights/features/Authentication/data/models/authentication.dart'
    as _i2;
import 'package:dark_knights/features/Authentication/domain/entities/authentication_entitiy.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticationModel_0 extends _i1.SmartFake
    implements _i2.AuthenticationModel {
  _FakeAuthenticationModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}

/// A class which mocks [AuthenticationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRemoteDataSource extends _i1.Mock
    implements _i5.AuthenticationRemoteDataSource {
  MockAuthenticationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthenticationModel> signup(_i6.Authentication? newuser) =>
      (super.noSuchMethod(
        Invocation.method(
          #signup,
          [newuser],
        ),
        returnValue: _i4.Future<_i2.AuthenticationModel>.value(
            _FakeAuthenticationModel_0(
          this,
          Invocation.method(
            #signup,
            [newuser],
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationModel>);
  @override
  _i4.Future<_i2.AuthenticationModel> login(_i6.Authentication? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [user],
        ),
        returnValue: _i4.Future<_i2.AuthenticationModel>.value(
            _FakeAuthenticationModel_0(
          this,
          Invocation.method(
            #login,
            [user],
          ),
        )),
      ) as _i4.Future<_i2.AuthenticationModel>);
}

/// A class which mocks [AuthenticationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationLocalDataSource extends _i1.Mock
    implements _i7.AuthenticationLocalDataSource {
  MockAuthenticationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
