// Mocks generated by Mockito 5.4.1 from annotations
// in mobile_assessement/test/features/weather/domain/usecase/weather_usecase_test.dart.
// Do not manually edit this file.

// @dart=2.19

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mobile_assessement/core/error/failures.dart' as _i5;
import 'package:mobile_assessement/features/weather/data/model/weather_model.dart'
    as _i6;
import 'package:mobile_assessement/features/weather/domain/repository/weather_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i3.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WeatherModel>> getWeatherForCity(
          String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherForCity,
          [city],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.WeatherModel>>.value(
                _FakeEither_0<_i5.Failure, _i6.WeatherModel>(
          this,
          Invocation.method(
            #getWeatherForCity,
            [city],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.WeatherModel>>);
  @override
  _i4.Future<
      _i2
          .Either<_i5.Failure, List<_i6.WeatherModel>>> getFavoriteWeather() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteWeather,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.WeatherModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.WeatherModel>>(
          this,
          Invocation.method(
            #getFavoriteWeather,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WeatherModel>>>);
  @override
  _i4.Future<void> saveFavoriteCity(String? city) => (super.noSuchMethod(
        Invocation.method(
          #saveFavoriteCity,
          [city],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  _i4.Future<void> removeFavoriteCity(String? city) => (super.noSuchMethod(
        Invocation.method(
          #removeFavoriteCity,
          [city],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
