// Mocks generated by Mockito 5.4.0 from annotations
// in mobile_assessement/test/features/weather_forcast/data/repositories/weather_repository_implementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mobile_assessement/features/weather_forcast/data/datasources/weather_remote_data_source.dart'
    as _i4;
import 'package:mobile_assessement/features/weather_forcast/data/models/weather_forcast_model.dart'
    as _i3;
import 'package:mobile_assessement/features/weather_forcast/data/models/weather_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWeatherForecastModel_1 extends _i1.SmartFake
    implements _i3.WeatherForecastModel {
  _FakeWeatherForecastModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i4.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeatherModel> getCurrentWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [city],
        ),
        returnValue: _i5.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [city],
          ),
        )),
      ) as _i5.Future<_i2.WeatherModel>);
  @override
  _i5.Future<_i3.WeatherForecastModel> getWeatherForecast(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherForecast,
          [city],
        ),
        returnValue: _i5.Future<_i3.WeatherForecastModel>.value(
            _FakeWeatherForecastModel_1(
          this,
          Invocation.method(
            #getWeatherForecast,
            [city],
          ),
        )),
      ) as _i5.Future<_i3.WeatherForecastModel>);
}
