// Mocks generated by Mockito 5.4.0 from annotations
// in dartsmiths/test/features/profile/data/repositories/get_user_profile_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartsmiths/core/network_info.dart' as _i5;
import 'package:dartsmiths/features/profile/data/datasources/user_profile_remote_data_source.dart'
    as _i3;
import 'package:dartsmiths/features/profile/data/models/user_profile_models.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileModel_0 extends _i1.SmartFake
    implements _i2.UserProfileModel {
  _FakeUserProfileModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRemoteDataSource extends _i1.Mock
    implements _i3.UserProfileRemoteDataSource {
  MockUserProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserProfileModel> getUserProfile(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.UserProfileModel>.value(_FakeUserProfileModel_0(
          this,
          Invocation.method(
            #getUserProfile,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.UserProfileModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isNetworkAvailable => (super.noSuchMethod(
        Invocation.getter(#isNetworkAvailable),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
